apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space
  template:
    metadata:
      labels:
        app: space
    spec:
      containers:
        - name: space
          image: niperx/space:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "space-redis"
            - name: REDIS_PORT
              value: "6379"